name:                astar
version:             0.1.0.0
github:              "donghankim/astar"
license:             MIT
author:              "Donghan Kim"
maintainer:          "dk3245@columbia.edu"
copyright:           "2022 Donghan Kim"

extra-source-files:
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/astar#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- containers
- pqueue
- parallel

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  seq:
    main:                Main.hs
    source-dirs:         seqApp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    - -eventlog
    dependencies:
    - astar
    when:
    - condition: false
      other-modules: Paths_astar

  par:
    main:                Main.hs
    source-dirs:         parApp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    - -eventlog
    dependencies:
    - astar
    when:
    - condition: false
      other-modules: Paths_astar

tests:
  seq-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - astar
